# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required
dist: focal
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: change
    recipients:
      - anthony.remazeilles@tecnalia.com
env:
  global:
    - CATKIN_PARALLEL_TEST_JOBS=-p1
    - ROS_PARALLEL_TEST_JOBS=-j1
  matrix:
    - ROS_DISTRO="noetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_INSTALL=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
##  - source ./travis.sh  # Enable this when you have a package-local script