#!/usr/bin/env python
"""
@package {packageName}
@file {componentName}
@author {packageAuthor}
@brief {packageDescription}
        Entry point to the node.
Copyright (C) {packageCopyright}
{packageLicense}
"""
from {packageName}.{componentName}_ros import main

if __name__ == '__main__':
    main()
